name: Build and deploy Node.js app to Azure Web App - PetColumbia

on:
  push:
    branches:
      - hml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies and build Vite project
        working-directory: ./my-react-app
        run: |
          npm ci
          NODE_ENV=production npm run build

      - name: Zip build output
        run: |
          cd my-react-app/dist
          zip -r ../../release.zip .

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B270EE28706E41D6B71B85AF4BA5A301 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F7EC51748B424E7094F227314CB87A88 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7610B091E31D409AB9647952CFB5A19F }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'PetColumbia'
          slot-name: 'Production'
          package: .

